KAYAKO-676 - Implemented Auto UTs for Kayako Android SDK app-library module
kayako/Kayako-Android-SDK pull request #32
Opened 2018-03-30 02:11 UTC by bhoomika-bathla

Initial coverage : 385
Final coverage : 1114
Lines covered : 729

2018-03-30 14:46 UTC, apparao-aremanda requested changes

2018-04-02 05:26 UTC, metalwihen requested changes
Hey. A few suggestions. 

1. Please use `testCompile` instead of `compile` for the test libraries. 

2. I've tried to run the tests locally but I am unable to load the following classes:
`com.aurea.unittest.commons.pojo.Testers`
`com.aurea.unittest.commons.pojo.chain.TestChain`
`com.aurea.unittest.commons.pojo.chain.Modifiers`
Is this restricted in some way?

Same issue, further explained here: trilogy-group/kayako-kre-java-client#3

2018-04-03 10:25 UTC, bartosz-rybusinski requested changes
In my humble opinion, there is no point in writing unit tests like that. 
They do not bring any value to our project they don't improve the quality. 
They:
 - don't protect me against regression 
 - don't test any functionality

In my humble opinion that it just the quantitive increase of coverage for the sake of reporting that coverage increase. 

All getters, setters and constructors should be tested by testing service layer class or other classes that invoke them. 
I'm afraid that I will have to reject that PR and all other PRs like that unless @levboyarsky @gregoraurea   will tell me otherwise.

2018-04-03 12:55 UTC, bartosz-rybusinski approved these changes

2018-04-03 13:59 UTC, apparao-aremanda approved these changes

2018-04-03 14:05 UTC, merged